/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.romannumeral;

class RomanNumeralApplicationTest {
    // @Test void appHasAGreeting() {
    //     RomanNumeralApplication classUnderTest = new RomanNumeralApplication();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    // }
}
